srpmod/urls.py
from django.urls import re_path
from . import views

app_name = 'srpmod'  # Put this before the actual module in the load order.

urlpatterns = [
    re_path(r'^set_char/(?P<fleet_id>(\w+))/$', views.srp_set_payment_character, name='set_char'),
    re_path(r'^set_char/$', views.srp_set_payment_character, name='set_char'),
    re_path(r'^open_id/(?P<id>(\w+))/$', views.srp_open_info, name='open_id'),
]

srpmod/models.py
from django.db import models
from django.contrib.auth.models import User
from esi.models import Token

class SrpPaymentToken(models.Model):
    user = models.OneToOneField(User,
                                primary_key=True,
                                on_delete=models.CASCADE,
                                related_name='srp_character')
    token = models.ForeignKey(Token, on_delete=models.CASCADE)

    class Meta:
        permissions = (('view_global_srp_stats', 'Can View All SRP Stats'),
                       ('view_own_srp_stats', 'Can View Personal SRP Stats'))

srpmod/views.py
import logging
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.decorators import permission_required
from django.http import Http404, HttpResponse
from django.shortcuts import render, redirect
from django.utils.translation import gettext_lazy as _
from django.db.models import Sum
from esi.decorators import token_required
from allianceauth.srp.models import SrpFleetMain
from allianceauth.srp.models import SrpUserRequest
from .models import SrpPaymentToken

from django.db.models import Sum, F
from dateutil.relativedelta import relativedelta
from django.utils import timezone
from allianceauth.srp.models import SrpUserRequest
import copy

logger = logging.getLogger(__name__)

from . import providers

@login_required
@permission_required('srp.access_srp')
def srp_fleet_view(request, fleet_id):
    logger.debug("srp_fleet_view called by user %s for fleet id %s" % (request.user, fleet_id))
    try:
        fleet_main = SrpFleetMain.objects.get(id=fleet_id)
    except SrpFleetMain.DoesNotExist:
        raise Http404
    context = {"fleet_id": fleet_id, "fleet_status": fleet_main.fleet_srp_status,
               "srpfleetrequests": fleet_main.srpuserrequest_set.select_related('character').order_by('srp_ship_name'),
               "totalcost": fleet_main.total_cost}

    return render(request, 'srpmod/data.html', context=context)


@login_required
@permission_required('auth.srp_management')
@token_required(['esi-ui.open_window.v1', 'esi-location.read_online.v1'])
def srp_set_payment_character(request, token, fleet_id=None):
    if token:
        srp_link = False
        try:
            srp_link = SrpPaymentToken.objects.get(user=request.user)
        except:
            pass
        if srp_link:
            srp_link.token = token
            srp_link.save()
        else:
            SrpPaymentToken.objects.create(user=request.user, token=token)
    messages.success(request,
                    _("Linked SRP Payments Character: {}".format(token.character_name)))
    if fleet_id:
        return redirect("srp:fleet", fleet_id)
    else:
        return redirect("srp:management")


@login_required
@permission_required('auth.srp_management')
def srp_open_info(request, id=None):
    try:
        if id:
            linked = request.user.srp_character
            if linked:
                online = providers.provider.client.Location.get_characters_character_id_online(character_id=linked.token.character_id, _request_options=providers.get_operation_auth_headers(linked.token)).result()
                if online.get('online', False):
                    providers.provider.client.User_Interface.post_ui_openwindow_information(target_id=id, _request_options=providers.get_operation_auth_headers(linked.token)).result()

        return HttpResponse("Success!")
    except:
        return HttpResponse("Failed!")


@login_required
@permission_required('srp.access_srp')
def srp_management(request, all=False):
    logger.debug("srp_management called by user %s" % request.user)
    fleets = SrpFleetMain.objects.select_related('fleet_commander').prefetch_related('srpuserrequest_set').all()

    now = timezone.now()
    dt = now - relativedelta(months=12)
    output_array={}
    fleet_breakout = SrpUserRequest.objects.select_related('srp_fleet_main')\
                            .filter(srp_fleet_main__fleet_time__gte=dt)\
                            .values('srp_fleet_main')\
                            .annotate(total_cost=Sum('srp_total_amount'))\
                            .annotate(fc_name=F('srp_fleet_main__fleet_commander__character_name'))\
                            .annotate(fleet_date=F('srp_fleet_main__fleet_time'))\
                            .order_by('-fleet_date')

    output_areay_scafold = {}
    global_srp = {}

    try:
        tempdate = fleet_breakout.filter().last().get('fleet_date')
        tempdate = tempdate.replace(day = 1).replace(hour = 0).replace(minute = 0)
        while tempdate < timezone.now():
            date_str = tempdate.strftime("%Y-%m")
            output_areay_scafold[date_str] = 0
            tempdate = tempdate + relativedelta(months=1)

        global_srp = copy.deepcopy(output_areay_scafold)

        for fleet in fleet_breakout:
            if fleet.get('fc_name') not in output_array:
                output_array[fleet.get('fc_name')] = copy.deepcopy(output_areay_scafold)
            try:
                date_str = fleet.get('fleet_date').strftime("%Y-%m")
                output_array[fleet.get('fc_name')][date_str] += fleet.get('total_cost')
                global_srp[date_str] += fleet.get('total_cost')
            except:
                pass
    except:
        pass
    if not all:
        fleets = fleets.filter(fleet_srp_status="")
    else:
        logger.debug("Returning all SRP requests")
    totalcost = fleets.aggregate(total_cost=Sum('srpuserrequest__srp_total_amount')).get('total_cost', 0)
    context = {"srpfleets": fleets, "totalcost": totalcost, 'graph':output_array,'graph_label':output_areay_scafold,'all_srp':global_srp}
    return render(request, 'srpmod/management.html', context=context)

srpmod/templates/srpmod/all_users.html
{% extends "allianceauth/base.html" %}
{% load bootstrap %}
{% load static %}
{% load i18n %}

{% load humanize %}
{% block page_title %}All SRP Requests{% endblock page_title %}
{% block extra_css %}
    {% include 'bundles/datatables-css.html' %}
    {% include 'bundles/x-editable.css.html' %}
    <link href="{% static 'css/checkbox.css' %}" rel="stylesheet" type="text/css">
    <style>
        .copy-text-fa-icon:hover {
            cursor: pointer;
        }
        .radio label, .checkbox label {
            padding-left: 10px;
        }
        .editable {
            width:150px;
            text-align: center;
        }
        .editableform .form-control {
            width: 95%;
            text-align: center;
            margin-left: 10px;
        }

        .editable-input {
            width: 95%;
        }
        .radio, .checkbox {
            margin-top: 0px;
            margin-bottom: 0px;
        }
        .editable-error-block {
            white-space: nowrap;
        }
        .editable-click, a.editable-click, a.editable-click:hover {
            border-bottom: none;
        }
        .tooltip-inner {
            white-space:pre;
            max-width: none;
        }
    </style>
{% endblock extra_css %}

{% block content %}
    <div class="col-lg-12">
        <div class="row">
            <h1 class="page-header text-center">{% translate "All SRP Requests" %}
            </h1>

            {% if srpfleetrequests %}
                <form method="POST">
                    {% csrf_token %}
                    <div class="alert alert-info" role="alert">
                        <div class="text-right">
                            <b><span style="padding-right:2.5em">{% translate "Total Losses:" %} {{ srpfleetrequests.count }}</span></b>
                            <b><span style="padding-right:2.5em">{% translate "Total ISK Cost:" %} {{ totalcost | intcomma }}</span></b>
                        </div>
                    </div>
                    <div class="table-responsive">
                        <table class="table srplist">
                            <thead>
                                <th class="text-center">{% translate "Pilot Name" %}</th>
                                <th class="text-center">{% translate "Killboard Link" %}</th>
                                <th class="text-center">{% translate "Fleet Link" %}</th>
                                <th class="text-center">{% translate "Additional Info" %}</th>
                                <th class="text-center">{% translate "Ship Type" %}</th>
                                <th class="text-center">{% translate "Killboard Loss Amt" %}</th>
                                <th class="text-center">{% translate "SRP Amount" %}</th>
                                <th class="text-center">{% translate "Post Time" %}</th>
                                <th class="text-center">{% translate "Status" %}</th>
                                <th class="text-center">{% translate "SRP Notes" %}</th>
                            </thead>

                            <tbody>
                            {% for srpfleetrequest in srpfleetrequests %}
                                <tr>
                                    <td class="text-center">
                                        {% if srpfleetrequest.character.alliance.alliance_ticker %}
                                            {{ srpfleetrequest.character.alliance.alliance_ticker }}
                                        {% endif %}
                                        [{{ srpfleetrequest.character.corporation.corporation_ticker }}]
                                        {{ srpfleetrequest.character.character_name }}&nbsp;<i class="copy-text-fa-icon far fa-copy" data-clipboard-text="{{ srpfleetrequest.character.character_name }}"></i>
                                        </span>
                                    </td>
                                    <td class="text-center">
                                        <a href="{{ srpfleetrequest.killboard_link }}"
                                        target="_blank" class="label label-warning">Link</a>
                                    </td>
                                    <td class="text-center">
                                        <a href="{% url 'echo_srp:fleet' srpfleetrequest.srp_fleet_main.id %}"
                                        target="_blank" class="label label-warning">Link</a>
                                    </td>
                                    <td class="text-center">{{ srpfleetrequest.additional_info }}</td>
                                    <td class="text-center">{{ srpfleetrequest.srp_ship_name }}</td>
                                    <td class="text-center" data-sort="{{ srpfleetrequest.kb_total_loss }}">{{ srpfleetrequest.kb_total_loss | intcomma }} ISK</td>
                                    <td class="text-center" data-sort="{{ srpfleetrequest.srp_total_amount }}">{{ srpfleetrequest.srp_total_amount | intcomma }} ISK</td>
                                    <td class="text-center" data-sort="{{ srpfleetrequest.post_time | date:"Y-m-d H:i" }}">{{ srpfleetrequest.post_time | date:"Y-M-d H:i" }}</td>
                                    <td class="text-center">
                                        {% if srpfleetrequest.srp_status == "Approved" %}
                                            <div class="label label-success">
                                                {% translate "Approved" %}
                                            </div>
                                        {% elif srpfleetrequest.srp_status == "Rejected" %}
                                            <div class="label label-danger">
                                                {% translate "Rejected" %}
                                            </div>
                                        {% else %}
                                            <div class="label label-warning">
                                                {% translate "Pending" %}
                                            </div>
                                        {% endif %}
                                    </td>
                                    {% if srpfleetrequest.srpuserrequestnotes %}
                                    <td class="text-center">{{ srpfleetrequest.srpuserrequestnotes.srp_notes }}</td>
                                    {% else %}
                                    <td class="text-center"></td>
                                    {% endif %}
                                </tr>
                            {% endfor %}
                            <tbody>

                        </table>
                    </div>
                    <div class="alert alert-info" role="alert">
                        <div class="text-right">
                            <b><span style="padding-right:2.5em">{% translate "Total Losses:" %} {{ srpfleetrequests.count }}</span></b>
                            <b><span style="padding-right:2.5em">{% translate "Total ISK Cost:" %} {{ totalcost | intcomma }}</span></b>
                        </div>
                    </div>
                </form>
            {% else %}
                <div class="alert alert-warning text-center">
                    {% translate "No SRP requests for this user." %}
                </div>
            {% endif %}
        </div>
    </div>
{% endblock content %}

{% block extra_javascript %}
    {% include 'bundles/datatables-js.html' %}
    {% include 'bundles/x-editable-js.html' %}
    {% include 'bundles/moment-js.html' %}
    {% include 'bundles/clipboard-js.html' %}

    <script>
        var clipboard = new ClipboardJS('.copy-text-fa-icon');
        clipboard.on('success', function (e) {
        console.info('Action:', e.action);
        console.info('Text:', e.text);
        console.info('Trigger:', e.trigger);

        e.clearSelection();
        });

        clipboard.on('error', function (e) {
        console.error('Action:', e.action);
        console.error('Trigger:', e.trigger);
        });
    </script>
{% endblock extra_javascript %}

{% block extra_script %}
    $(document).ready(function() {
        $.fn.editable.defaults.mode = 'inline';
        $.fn.editable.defaults.showbuttons = false;
        $.fn.editable.defaults.highlight = "#AAFF80";

        $.fn.dataTable.moment = function(format, locale) {
            let types = $.fn.dataTable.ext.type;

            // Add type detection
            types.detect.unshift(function(d) {
                return moment(d, format, locale, true).isValid() ?
                    'moment-' + format :
                    null;
            });

            // Add sorting method - use an integer for the sorting
            types.order[ 'moment-' + format+'-pre' ] = function(d) {
                return moment(d, format, locale, true).unix();
            };
        };
        $.fn.dataTable.moment('YYYY-MMM-D, HH:mm');

        $('.srp').editable({
            display: function(value, response) {
                return false;
            },
            success: function(response, newValue) {
                newValue = parseInt(newValue);
                let newValueOutput = newValue.toLocaleString() + " ISK";

                $(this).html(newValueOutput.bold());
            },
            validate: function(value) {
                if (value === null || value === '') {
                    return 'Empty values not allowed';
                }
            }
        });

        $('.srp').on('hidden', function(e, reason){
            if(reason === 'save' || reason === 'nochange') {
                let $next = $(this).closest('tr').next().find('.editable');

                setTimeout(function() {
                    $next.editable('show');
                }, 400);
            }
        });

        $('table.srplist').DataTable({
            "order": [[ 6, "asc" ]],
            "paging": true,
            "columnDefs": [
                {
                    "targets": [1, 8],
                    "orderable": false
                },
                {
                    "targets": [4, 5],
                    "type": "num"
                }
            ],
            "stateSave": true,
            "stateDuration": 0
        });

        // tooltip
        $("[rel=tooltip]").tooltip({ placement: 'top'});
    });
{% endblock extra_script %}

srpmod/templates/srpmod/management.html
{% extends "allianceauth/base.html" %}
{% load bootstrap %}
{% load static %}
{% load i18n %}
{% load color %}

{% load humanize %}

{% block page_title %}{% trans "Srp Management" %}{% endblock page_title %}
{% block extra_css %}{% endblock extra_css %}

{% block content %}
    <div class="col-lg-12">
        <div class="row">
            <h1 class="page-header text-center">{% trans "SRP Management" %}
                <div class="text-right">
                    {% if perms.auth.srp_management %}
                        <a href="{% url 'srp:all' %}" class="btn btn-primary">
                            {% trans "View All" %}
                        </a>
                        <a href="{% url 'srpmod:set_char' %}" class="btn btn-success">
                            {% trans "Linked Character: " %}{% if request.user.srp_character %}{{request.user.srp_character.token.character_name}}{% else %}{% trans "None" %}{% endif %}
                        </a>
                    {% endif %}
                    {% if perms.srp.add_srpfleetmain or perms.auth.srp_management %}
                        <a href="{% url 'srp:add' %}" class="btn btn-success">
                            {% trans "Add SRP Fleet" %}
                        </a>
                    {% endif %}
                </div>
            </h1>
            {% if perms.srp.add_srpfleetmain or perms.auth.srp_management %}
            <div class="clearfix"></div>
            <div class="col-md-12 panel panel-default"> 
                <div class="chartjs-size-monitor">
                    <div class="chartjs-size-monitor-expand">
                        <div class="">

                        </div>
                    </div>
                    <div class="chartjs-size-monitor-shrink">
                        <div class="">

                        </div>
                    </div>
                </div>
                <canvas id="canvas" height="350" class="chartjs-render-monitor"></canvas>
            </div>
            <div class="clearfix"></div>
            {% endif %}
            <div class="alert alert-info" role="alert">
                <div class="text-right">
                    <b>{% trans "Total ISK Cost:" %} {{ totalcost | intcomma }}</b>
                </div>
            </div>
            {% if srpfleets %}
                <div class="table-responsive">
                    <table class="table">
                        <tr>
                            <th class="text-center">{% trans "Fleet Name" %}</th>
                            <th class="text-center">{% trans "Fleet Time" %}</th>
                            <th class="text-center">{% trans "Fleet Doctrine" %}</th>
                            <th class="text-center">{% trans "Fleet Commander" %}</th>
                            <th class="text-center">{% trans "Fleet AAR" %}</th>
                            <th class="text-center">{% trans "Fleet SRP Code" %}</th>
                            <th class="text-center">{% trans "Fleet ISK Cost" %}</th>
                            <th class="text-center">{% trans "SRP Status" %}</th>
                            <th class="text-center">{% trans "Pending Requests" %}</th>
                            <th class="text-center">{% trans "Actions" %}</th>
                        </tr>
                        
                        {% for srpfleet in srpfleets %}
                            <tr>
                                <td class="text-center">
                                    <div class="label label-info">
                                        {{ srpfleet.fleet_name }}
                                    </div>
                                </td>
                                <td class="text-center">{{ srpfleet.fleet_time | date:"Y-m-d H:i" }}</td>
                                <td class="text-center">{{ srpfleet.fleet_doctrine }}</td>
                                <td class="text-center">
                                    <div class="label label-success">
                                        {{ srpfleet.fleet_commander.character_name }}
                                    </div>
                                </td>
                                <td class="text-center">
                                    {%  if srpfleet.fleet_srp_aar_link %}
                                        <a href="{{ srpfleet.fleet_srp_aar_link }}" target="_blank" class="label label-primary">{% trans 'Link' %}</a>
                                    {%  endif %}
                                </td>
                                <td class="text-center">
                                    {% if srpfleet.fleet_srp_code %}
                                        <a class="label label-warning" href="{% url 'srp:request' srpfleet.fleet_srp_code %}">{{ srpfleet.fleet_srp_code }}</a>
                                    {% else %}
                                        <div class="label label-danger">
                                            {% trans "Disabled" %}
                                        </div>
                                    {% endif %}
                                </td>
                                <td class="text-center">ISK: {{ srpfleet.total_cost | intcomma }}</td>

                                <td class="text-center">
                                    {% if srpfleet.fleet_srp_status == "" %}
                                        <div class="label label-warning">
                                            {% trans "Pending" %}
                                        </div>
                                    {% else %}
                                        <div class="label label-success">
                                            {% trans "Completed" %}
                                        </div>
                                    {% endif %}
                                </td>
                                <td class="text-center">
                                    <div class="label label-warning">{{ srpfleet.pending_requests }}</div>
                                </td>
                                <td class="text-center">

                                    <a href="{% url 'srp:fleet' srpfleet.id %}" class="btn btn-primary" title="View">
                                        <span class="glyphicon glyphicon-eye-open"></span>
                                    </a>

                                    {% if perms.auth.srp_management %}
                                        <a href="{% url 'srp:edit' srpfleet.id %}" class="btn btn-info" title="Edit">
                                            <span class="glyphicon glyphicon-pencil"></span>
                                        </a>

                                        <a href="{% url 'srp:remove' srpfleet.id %}" onclick="return confirm('{% trans "Are you sure you want to delete this SRP code and its contents?" %}')" class="btn btn-danger" title="Remove">
                                            <span class="glyphicon glyphicon-trash"></span>
                                        </a>
                                        {% if srpfleet.fleet_srp_code %}
                                            <a href="{% url 'srp:disable' srpfleet.id %}" class="btn btn-warning" title="Disable">
                                                <span class="glyphicon glyphicon-remove-sign"></span>
                                            </a>
                                        {% else %}
                                            <a href="{% url 'srp:enable' srpfleet.id %}" class="btn btn-success" title="Enable">
                                                <span class="glyphicon glyphicon-ok-sign"></span>
                                            </a>
                                        {% endif %}

                                    {% endif %}
                                </td>
                            </tr>
                        {% endfor %}
                    </table>
                </div>
            {% else %}
                <div class="alert alert-warning text-center">
                    {% trans "No SRP fleets created." %}
                </div>
            {% endif %}
        </div>
    </div>

{% endblock content %}
{% block extra_javascript %}
{% if perms.srp.add_srpfleetmain or perms.auth.srp_management %}
<script src="https://cdnjs.cloudflare.com/ajax/libs/Chart.js/3.0.0-alpha/Chart.min.js"></script>
<script>
    var config = {
        type: 'line',
        data: {
            labels: [{% for date_str, val in graph_label.items %}"{{date_str}}",{% endfor %}],
            datasets: [
                {% for fc,data in graph.items %}
                {
                    label: "{{fc}}",
                    borderColor: "{% random_colour %}",
                    data: [{% for fleet_month, isk in data.items %}{{isk}},{% endfor %}],
                    fill: false,
                },
                {% endfor %}
                {
                    label: "All SRP",
                    borderColor: "#FF0000",
                    data: [{% for fleet_month, isk in all_srp.items %}{{isk}},{% endfor %}],
                    fill: false,
                },

            ]
        },  
        
        options: {
            responsive: true,
            maintainAspectRatio: false,
            title: {
                display: true,
                text: 'FC SRP Use'
            },
            tooltips: {
                mode: 'index',
                intersect: false,
                filter: function (tooltipItem, data) {
                    if (parseInt(tooltipItem.value)<1) {
                        return false;
                    } else {
                        return true;
                    }
                }                
            },
            hover: {
                mode: 'nearest',
                intersect: true
            },
            scales: {
                xAxes: [{
                    display: true,
                    scaleLabel: {
                        display: true,
                        labelString: 'Month'
                    }
                }],
                yAxes: [{
                    display: true,
                    scaleLabel: {
                        display: true,
                        labelString: 'Isk'
                    }
                }]
            }
        }
    };

    window.onload = function() {
			var ctx = document.getElementById('canvas').getContext('2d');
			window.myLine = new Chart(ctx, config);
        };

</script>
{% endif %}
{% endblock %}